# Site Settings
baseurl: ""
url: "https://hamsik2rang.github.io"

# Blog Settings
theme_settings:
  title: Hamsik2rang's Blog
  favicon: assets/favicons/favicon.ico

  # Profile Settings
  profile:
    image: assets/img/profile2.jpg
    username: Im Yongsik
    description: A Programmer who interested in Game Engine and Computer Graphics
    experience:
      - start: 2016-03
        end:
        experience: Enter KNU, Kongju National University
      - start: 2020-01
        end: 2020-12
        experience: Vice president in Striking Arts - Game Dev Club in KNU
      - start: 2020-11
        end: 2020-11
        experience: Top prize at the Capstone Project of the Department of Software at KNU
      - start: 2023-02
        end:
        experience: Join Com2us
    skills:
      - skill: C
        value: 85 # Percent value
      - skill: C++
        value: 75
      - skill: C#
        value: 60
      - skill: Vulkan
        value: 70
      - skill: Metal
        value: 60

  # Icons
  icons:
    email: lvhi7121@gmail.com # Full email address, e.g. "sample@google.com"
    linkedin: # Full URL
    github: Hamsik2rang
    gitlab:
    bitbucket:
    google_plus:
    twitter:
    youtube: UCiAe__zoEwjE4s9f5YPKO0w
    facebook:
    instagram: t_was_sik

  # Disqus
  disqus_shortname: hamsik2rang

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-sitemap]
bootstrap:
  assets: true

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n"
incremental: false
