# Site Settings
baseurl: ""
url : "https://naye0ng.github.io"

# Blog Settings
theme_settings :
  title : Hamsik2rang's Blog
  favicon : assets/favicons/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/smile.png
    username : Im Yongsik
    description : A Student who along with Game dev
    experience :
      - start : 2016-03
        end : 
        experience : Enter KNU, Kongju nationa university
      - start: 2020-01
        end : 2020-12
        experience : Vice president in Striking Arts - Game dev club in KNU
    skills : 
      - skill : C
        value : 85  # Percent value
      - skill : C++
        value : 75
        
      
  # Icons
  icons :
    email:  lvhi7121@gmail.com # Full email address, e.g. "sample@google.com"
    linkedin:  # Full URL 
    github: Hamsik2rang
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube: UCiAe__zoEwjE4s9f5YPKO0w
    facebook:
    instagram: that_was_sik

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate]
bootstrap:
  assets: true
