baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Hamsik2rang's blog"
theme = 'typo'

# Google analytics code
googleAnalytics = "G-xxxxxxxxx"

[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "A Tech Blog"

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = '임용식(Yongsik Im)'
profileImage = "/images/profile.jpg"
homeIntroContent = """
안녕하세요. 방문해주셔서 감사합니다.\n
현재 [컴투스](https://com2us.com/)에서 엔진 프로그래머로 일하며 게임 엔진을 개발하고 있습니다.  
게임 엔진 아키텍쳐, 실시간 렌더링, GPGPU 등의 주제를 탐구하며, 블로그를 통해 다양한 기술과 경험을 공유하고 싶습니다.  
"""

# Collection to display on home
homeCollectionTitle = 'Posts'
homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
[params.breadcrumbs]
enabled = true
showCurrentPage = true
home = "Home"

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/hamsik2rang/"

[[params.social]]
name = "github"
url = "https://github.com/hamsik2rang"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "about"
url = "/about"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'github'


# Giscus comments
[params.giscus]
enable = false
repo = "hamsik2rang/hamsik2rang.github.io"
repoid = "hamsik2rang"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"

# Caches for Github Pages Deploy
[caches]
  [caches.images]
    dir = ':cacheDir/images'